title: My Personal Page
logo: /assets/img/delara-forghani.jpg
description: This is a personal profile and a brief introduction about myself.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
